name: CapovillaFake
version: '1.0'
main: br.com.vitorcapovilla.capovillafake.CapovillaFake
api-version: '1.19'

depend: [ ProtocolLib ]

commands:
  fake:
    description: Comando para alterar o nome de exibição.
    usage: /fake [restore|random|<novo_nome>]